version: '3.11.9'
services:
  web:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "443:443"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password