# Generated by Django 5.0.4 on 2024-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('opcion1', 'INFO'), ('opcion2', 'ERROR'), ('opcion3', 'SUCCESS')], max_length=50)),
                ('observacion', models.CharField(max_length=255)),
                ('nombre_aplicacion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('opcion1', 'Automatizacion'), ('opcion2', 'Seguridad'), ('opcion3', 'Registro')], max_length=50)),
            ],
        ),
    ]
