# Generated by Django 5.0.7 on 2025-03-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='id_registro',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
