# Generated by Django 5.0.4 on 2024-07-25 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtrlCapacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la sesión')),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('moderador', models.CharField(max_length=60)),
                ('area_encargada', models.CharField(choices=[('opcion1', 'Opción 1'), ('opcion2', 'Opción 2')], max_length=20)),
                ('tema', models.CharField(max_length=60)),
            ],
        ),
    ]
