# Generated by Django 5.0.4 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('CERRADA', 'CERRADA')], default='ACTIVA', max_length=10),
            preserve_default=False,
        ),
    ]
