# Generated by Django 5.0.4 on 2024-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0002_ctrlcapacitaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('CERRADA', 'CERRADA')], default='ACTIVA', max_length=10),
        ),
    ]
