# Generated by Django 5.0.7 on 2024-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0003_alter_ctrlcapacitaciones_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='area_encargada',
            field=models.CharField(max_length=200),
        ),
    ]
