# Generated by Django 5.0.7 on 2024-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0004_alter_ctrlcapacitaciones_area_encargada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
