# Generated by Django 5.0.7 on 2024-08-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0005_ctrlcapacitaciones_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctrlcapacitaciones',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='qr_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
