# Generated by Django 5.0.7 on 2024-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0006_remove_ctrlcapacitaciones_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='objetivo',
            field=models.CharField(default='Redactar el objetivo de la capacitación', max_length=400),
        ),
    ]
