# Generated by Django 5.0.7 on 2024-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0007_ctrlcapacitaciones_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='area_encargada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='objetivo',
            field=models.CharField(default='Redactar el objetivo de la capacitación', max_length=160),
        ),
    ]
