# Generated by Django 5.0.7 on 2024-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0009_alter_ctrlcapacitaciones_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='objetivo',
            field=models.CharField(max_length=161),
        ),
    ]
