# Generated by Django 5.0.7 on 2024-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0010_alter_ctrlcapacitaciones_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('VIRTUAL', 'VIRTUAL'), ('MIXTA', 'MIXTA')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='privacidad',
            field=models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default='ABIERTA', max_length=20, verbose_name='Privacidad'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='responsable',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='tipo',
            field=models.CharField(choices=[('Capacitación', 'Capacitación'), ('Reunión', 'Reunión'), ('Bienestar', 'Bienestar')], default='Capacitación', max_length=20, verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='total_invitados',
            field=models.IntegerField(default=0, verbose_name='Total Asistentes'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='url_reunion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de la Reunión'),
        ),
        migrations.AlterField(
            model_name='ctrlcapacitaciones',
            name='objetivo',
            field=models.CharField(max_length=255),
        ),
    ]
