# Generated by Django 5.0.7 on 2024-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0011_ctrlcapacitaciones_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
