# Generated by Django 5.0.7 on 2025-03-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learning', '0013_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='archivo_presentacion',
            field=models.URLField(blank=True, null=True, verbose_name='Archivo Presentación'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='temas',
            field=models.TextField(blank=True, null=True, verbose_name='Temas'),
        ),
        migrations.AddField(
            model_name='ctrlcapacitaciones',
            name='user',
            field=models.CharField(default='user', max_length=250),
        ),
    ]
