# Generated by Django 5.0.7 on 2025-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_date', models.DateField(verbose_name='Fecha del comprobante')),
                ('company', models.CharField(max_length=255, verbose_name='Compañía')),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula')),
                ('blob_url', models.URLField(max_length=500, verbose_name='URL del Blob')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
            ],
        ),
    ]
