# Generated by Django 5.0.7 on 2025-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIRCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante_date', models.DateField()),
                ('company', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=20)),
                ('blob_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='laborcertificate',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
